[package]
name = "oro-classic-resolver"
version = "0.1.0"
authors = ["Kat March√°n <kzm@zkat.tech>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
package-arg = { path = "../package-arg" }
rogga = { path = "../rogga" }

semver = "0.10.0"
thiserror = "1.0.20"
async-trait = "0.1.36"
