[package]
name = "oro-diagnostics"
version = "0.1.0"
authors = ["Kat March√°n <kzm@zkat.tech>"]
edition = "2018"

[dependencies]
url = "2.2.0"
thiserror = "1.0.22"
colored = "2.0.0"
oro-diagnostics-derive = { path = "./oro-diagnostics-derive" }
