[package]
name = "oro-config"
version = "0.1.0"
authors = ["Kat March√°n <kzm@zkat.tech>"]
edition = "2021"

[dependencies]
oro-config-derive = { path = "../oro-config-derive" }

clap = { workspace = true, features = ["derive"] }
config = { version = "0.9.3", features = ["toml"] }
miette = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
pretty_assertions = { workspace = true }
