[package]
name = "oro-config"
version = "0.1.0"
authors = ["Kat March√°n <kzm@zkat.tech>"]
edition = "2018"

[dependencies]
oro-config-derive = { path = "../oro-config-derive" }
oro-diagnostics = { path = "../oro-diagnostics" }
oro-diagnostics-derive = { path = "../oro-diagnostics/oro-diagnostics-derive" }

clap = { git = "https://github.com/zkat/clap" }
config = { version = "0.9.3", features = ["toml"] }
serde = { version = "1.0.103", features = ["derive"] }
thiserror = "1.0.22"

[dev-dependencies]
anyhow = "1.0.24"
tempfile = "3.1.0"
pretty_assertions = "0.6.1"
