[package]
name = "package-arg"
version = "0.1.0"
authors = ["Kat March√°n <kzm@zkat.tech>"]
edition = "2018"

[dependencies]
oro-error-code = { path = "../oro-error-code" }
semver = { path = "../oro-semver" }

url = "2.1.0"
nom = "5.0.1"
thiserror = "1.0.9"
percent-encoding = "2.1.0"
