[package]
name = "rogga"
version = "0.1.0"
authors = ["Kat March√°n <kzm@zkat.tech>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oro-client = { path = "../oro-client" }
oro-error-code = { path = "../oro-error-code" }
package-spec = { path = "../package-spec" }
cacache = { path = "../cacache", version = "8.0.0" }
oro-node-semver = { path = "../oro-node-semver" }
oro-manifest = { path = "../oro-manifest" }

async-tar = "0.2.0"
async-std = { version = "1.6.2", features = ["attributes", "unstable"] }
async-compression = { version = "0.3.5", features = ["gzip", "futures-io"] }
bincode = "1.3.1"
futures = "0.3.5"
ssri = "6.0.0"
thiserror = "1.0.20"
async-trait = "0.1.36"
http-types = "2.3.0"
chrono = { version = "0.4.13", features = ["serde"] }
serde_json = "1.0.56"
log = "0.4.11"
serde = "1.0.114"

# We can remove this after https://github.com/http-rs/http-types/issues/205 is
# fixed.
url = { version = "2.1.1", features = ["serde"] }
mkdirp = "1.0.0"
