[package]
name = "oro-client"
version = "0.3.11"
authors = ["Kat March√°n <kzm@zkat.tech>"]
edition = "2021"
description = "Generic client for the HTTP NPM api."
license = "Apache-2.0"
repository = "https://github.com/orogene/orogene"
homepage = "https://github.com/orogene/orogene"
readme = "README.md"


[dependencies]
oro-common = { version = "=0.3.11", path = "../oro-common" }

futures = { workspace = true, features = ["io-compat"] }
miette = { workspace = true }
reqwest = { workspace = true, features = ["json", "gzip", "stream"] }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
http-cache-reqwest = { workspace = true }
reqwest-middleware = { workspace = true }

[dev-dependencies]
async-std = { workspace = true, features = ["attributes", "tokio1"] }
maplit = { workspace = true }
pretty_assertions = { workspace = true }
wiremock = { workspace = true }
