[package]
name = "oro-client"
version = "0.1.0"
authors = ["Kat March√°n <kzm@zkat.tech>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oro-common = { path = "../oro-common" }

futures = { workspace = true, features = ["io-compat"] }
http-cache-reqwest = "0.6.0"
miette = { workspace = true }
reqwest-middleware = "0.2.0"
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
reqwest = { version = "0.11.12", features = ["json", "gzip", "stream"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
reqwest-wasm = { git = "https://github.com/tmpfs/reqwest", branch = "wasm-bytes-stream", features = ["json", "gzip", "stream"], package = "reqwest"}

[dev-dependencies]
async-std = { workspace = true, features = ["attributes", "tokio1"] }
maplit = { workspace = true }
pretty_assertions = { workspace = true }
wiremock = { workspace = true }
